name: Release Builder

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [published]

jobs:
  windows-x86_64-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run Windows Build Script
        run: scripts\build_windows.bat
        shell: cmd

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: ringcentral_mass_sms-x86_64.exe
          path: dist/ringcentral_mass_sms.exe

      - name: Upload to Release (Windows)
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/ringcentral_mass_sms.exe
          asset_name: ringcentral_mass_sms-x86_64.exe
          asset_content_type: application/octet-stream
